import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import {faYoutube} from '@fortawesome/free-brands-svg-icons'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="show_menuitems" className={styles['my-menu']}>
        <div className="menu-box">
          <span>
            <i onclick="hide_menu()" className={styles['flaticon-cancel']}></i>
          </span>
          <ul>
            <li>
              <a onclick="hide_menu()" href="#home">
                Home
              </a>
            </li>
            <li>
              <a onclick="hide_menu()" href="#about">
                Specialization
              </a>
            </li>
            <li>
              <a onclick="hide_menu()" href="#resume">
                Resume
              </a>
            </li>
            <li>
              <a onclick="hide_menu()" href="#portfolio">
                Projects
              </a>
            </li>
            <li>
              <a onclick="hide_menu()" href="#textimonial">
                Reviews
              </a>
            </li>
            <li>
              <a onclick="hide_menu()" href="#contact">
                Contact
              </a>
            </li>
          </ul>
        </div>
      </div>
      <section className={styles.home}>
        <header>
          <div className="container">
            <div className={styles.main_nav}>
              <div className={styles.logo}>
                <h2>Stive Smith</h2>
              </div>
              <div className={styles.social_media}>
                <ul>
                  <li>
                    {/* <a>
                      <i className="flaticon-facebook"></i>
                    </a> */}
                  <FontAwesomeIcon icon={faCoffee} color="white"/>
                  <FontAwesomeIcon icon={faYoutube} color="white"/>
                  </li>
                  <li>
                    <a>
                      <i className="flaticon-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a>
                      <i className="flaticon-behance-big-logo"></i>
                    </a>
                  </li>
                  <li>
                    <a>
                      <i className="flaticon-linkedin"></i>
                    </a>
                  </li>
                  <li>
                    <a>
                      <i className="flaticon-dribbble"></i>
                    </a>
                  </li>
                </ul>
              </div>
              <div onclick="show_menu()" className="my-toogle">
                <span>
                  <i className="flaticon-menu"></i>
                </span>
              </div>
            </div>
          </div>
        </header>
        <div className="container">
          <div className="row">
            <div className={styles.my_wrapper}>
              <div className={styles.inter}>
                <h6>Introduce</h6>
              </div>
              <div className={styles.welcome_box}>
                <h3>
                  Welcome to<span>Smith Design</span>
                </h3>
              </div>
              <div className={styles.name_box}>
                <h1>
                  Hello my name is <span>Stive Smith.</span>
                </h1>
              </div>
              <div className={styles.line}></div>
            </div>
            <div className={styles.copy_right}>
              <h6>© Smith 2020</h6>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.about}>
        <div className="container">
          <div className="row">
            <div className={styles.wrapper}>
              <div className={styles.left_wrapper}>
                <div className={styles.content}>
                  <div className={styles.title}>
                    <h4>About me</h4>
                    <h2>
                      MY MISSION IS <span>DESIGN & DEVELOP</span>
                      THE BEST WEBSITES AROUND
                    </h2>
                    <p>
                      I love everything that has to do with Web design &
                      development, Graphic design, and I feel a true devotion
                      for typography. I have 3 years of experience working as a
                      UI Developer
                    </p>
                  </div>
                </div>
              </div>
              <div className={styles.right_wrapper}>
                <div className={styles.content._yt_er_ol}>
                  <div className={styles._re_uy_iu}>
                    <div className={styles._ol_ew_xs}>
                      <span>UI Development</span>
                      <span>70%</span>
                    </div>
                    <div className={styles.progress}>
                      <div
                        className="progress-bar my-bars"
                        role="progressbar"
                        aria-valuenow="0"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                    </div>
                  </div>
                  <div className={styles._re_uy_iu}>
                    <div className={styles._ol_ew_xs}>
                      <span>Design Concepts</span>
                      <span>65%</span>
                    </div>
                    <div className={styles.progress}>
                      <div
                        className="progress-bar my-bars"
                        role="progressbar"
                        aria-valuenow="0"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                    </div>
                  </div>
                  <div className={styles._re_uy_iu}>
                    <div className={styles._ol_ew_xs}>
                      <span>Communication</span>
                      <span>30%</span>
                    </div>
                    <div className={styles.progress}>
                      <div
                        className="progress-bar my-bars"
                        role="progressbar"
                        aria-valuenow="0"
                        aria-valuemin="0"
                        aria-valuemax="100"
                      ></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={styles.inter}>
                <h6>WHAT I DO</h6>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.resume}>
        <div className="container">
          <div className="row">
            <div className={styles.my_wrapper}>
              <div className={styles.left_wrapper}>
                <div className={styles.content}>
                  <div className={styles.head}>
                    <h2>Education</h2>
                  </div>
                  <div className={styles.list_inner}>
                    <ol>
                      <li>
                        <h4>Diploma in Multimedia</h4>
                        <h6>Animation Center Chennai</h6>
                        <span>Sep 05 2015 to Sep 05 2016 </span>
                        <p>
                          Every year, the number of people using the Internet is
                          increased to twice that of the previous year. Also,
                          the increase in various internet-enabled devices like
                          Mobile, Tablet, PC, and TV have turned over a new era
                          in the progress of Web development.
                        </p>
                      </li>

                      <li>
                        <h4>+2</h4>
                        <h6>Tamilnadu</h6>
                        <span>13-06-2012 to 01-03-2014</span>
                      </li>
                    </ol>
                  </div>
                </div>
              </div>
              <div className={styles.right_wrapper}>
                <div className={styles.content}>
                  <div className={styles.head}>
                    <h2>Experience</h2>
                  </div>
                  <div className={styles.list_inner}>
                    <ol>
                      <li>
                        <h4>Smarteye Technologies</h4>
                        <h6>Web Designer</h6>
                        <span>06-11-2017 Continued</span>
                        <p>
                          Website Templates, Bootstrap Templates, PHP Scripts
                          Web Design, Application Development, Technical Support
                        </p>
                      </li>
                    </ol>
                  </div>
                </div>
              </div>
              <div className={styles.inter}>
                <h6>RESUME</h6>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* <section className={styles.portfolio}>
        <div className="container">
          <div className="row">
            <div className={styles.my_wrapper}>
              <div className={styles.wrapper_box}>
                <div className={styles.content}>
                  <ul
                    className="nav nav-tabs border-0"
                    id="myTab"
                    role="tablist"
                  >
                    <li className="nav-item">
                      <a
                        className="nav-link active"
                        id="free-template"
                        data-toggle="tab"
                        href="#free"
                        role="tab"
                        aria-controls="free"
                        aria-selected="true"
                      >
                        Web Designing
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        className="nav-link"
                        id="premium-template"
                        data-toggle="tab"
                        href="#premium"
                        role="tab"
                        aria-controls="premium"
                        aria-selected="true"
                      >
                        Graphic Designing
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        className="nav-link"
                        id="others-template"
                        data-toggle="tab"
                        href="#others"
                        role="tab"
                        aria-controls="others"
                        aria-selected="true"
                      >
                        Others
                      </a>
                    </li>
                  </ul>

                  <div className="tab-content" id="myTabContent">
                    <div
                      className="tab-pane fade show active"
                      id="free"
                      role="tabpanel"
                      aria-labelledby="free-template"
                    >
                      <div className="content-list">
                        <ol>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/1.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/2.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/3.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/4.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/5.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/6.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/7.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/8.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                        </ol>
                      </div>
                    </div>

                    <div
                      className="tab-pane fade "
                      id="premium"
                      role="tabpanel"
                      aria-labelledby="premium-template"
                    >
                      <div className="content-list">
                        <ol>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/5.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/6.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/7.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/8.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/1.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/2.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/3.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/4.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                        </ol>
                      </div>
                    </div>

                    <div
                      className="tab-pane fade "
                      id="others"
                      role="tabpanel"
                      aria-labelledby="others-template"
                    >
                      <div className="content-list">
                        <ol>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/1.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/2.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/3.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                          <li>
                            <div className="_ok-vd_zs">
                              <figure>
                                <Image
                                  layout="fill"
                                  src="/images/abt/4.jpg"
                                ></Image>
                                <div className="inner-content">
                                  <a href="#">Live Preview</a>
                                </div>
                              </figure>
                            </div>
                          </li>
                        </ol>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={styles.inter}>
                <h6>Portfolio</h6>
              </div>
            </div>
          </div>
        </div>
      </section> */}

      <section className={styles.contact}>
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className={styles.heading}>
                <h2>Get in Touch</h2>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-12">
              <form action="#">
                <div className="row">
                  <div className="col-md-6 col-sm-12 col-xs-12">
                    <div className={styles['form-group']}>
                      <input
                        className={styles['form-control']}
                        name="121"
                        type="text"
                        required="name"
                        placeholder="Enter Your Name"
                      ></input>
                    </div>
                  </div>
                  <div className="col-md-6 col-sm-12 col-xs-12">
                    <div className={styles['form-group']}>
                      <input
                        className={styles['form-control']}
                        name="122"
                        type="text"
                        required="email"
                        placeholder="Enter Your Email"
                      ></input>
                    </div>
                  </div>
                  <div className="col-12">
                    <div className={styles['form-group']}>
                      <input
                        className={styles['form-control']}
                        name="123"
                        type="text"
                        required="subject"
                        placeholder="Subject (optinal)"
                      ></input>
                    </div>
                  </div>
                  <div className="col-12">
                    <div className={styles['form-group']}>
                      <textarea
                        className=""
                        cals="40"
                        rows="10"
                        name="124"
                        type="text"
                        placeholder="Message"
                      ></textarea>
                    </div>
                  </div>
                  <div className="col-12">
                    <div className="send">
                      <a href="#">Send</a>
                    </div>
                  </div>
                </div>
              </form>
              <div className={styles.inter}>
                <h6>Contact</h6>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
